### ISSUE TITLE
Is it there any limitation for sending iMessages? I mean, x iMessages x day?

### ISSUE THREAD

**Issue by alopezruiz** [linjunpop/imessage#11]
Hi @linjunpop 

Congrats for your code, is it there any limitation for sending iMessages? I mean, x iMessages x day?

And, could I choose which could be the account source of the iMessages I send?

Finally, is it any way so customer receiving this iMessages could not interact answering ? 

Thanks you

**Comment by linjunpop** [comment]
It depends on the iMessage service.
