### ISSUE TITLE
Error with send command

### ISSUE THREAD

**Issue by jbwl** [linjunpop/imessage#3]
With the current version on ruby 2.1.2 on Darwin (Yosemite), I am getting a 
`error: no implicit conversion of nil into String`
error on send, regardless of what the message content or receiving address contains.

**Comment by sabyari** [comment]
I'm having the same issue as jbwl

**Comment by sabyari** [comment]
Looks like this happens only when no -a(attachment) argument is included

**Comment by linjunpop** [comment]
`v0.1.1` should fix this.

**Comment by jbwl** [comment]
it does. Thank you!
